name: Build and Deploy

on:
  push:
    branches:
      - webgpu

jobs:
  build-and-publish-live-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}/"
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: demo
          folder: dist
